name: Auto-Translate Missing Locales

on:
  push:
    branches:
      - main
      - master
    paths:
      - 'en/**/*.json'
      - '*.json'
  workflow_dispatch:

jobs:
  translate:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install aiohttp

      - name: Run translation script
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          python translate_missing.py

      - name: Check for changes
        id: check_changes
        run: |
          git diff --quiet || echo "changes=true" >> $GITHUB_OUTPUT

      - name: Create branch and pull request
        if: steps.check_changes.outputs.changes == 'true'
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          BRANCH_NAME="auto-translation/$(date -u +'%Y-%m-%d-%H%M%S')"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git checkout -b "$BRANCH_NAME"
          git add -A
          git commit -m "chore: auto-translate missing locale entries"
          git push origin "$BRANCH_NAME"
          gh pr create --title "Auto-translate missing locale entries" \
            --body "Automated translation of missing locale entries generated on $(date -u +'%Y-%m-%d at %H:%M:%S UTC')." \
            --base main \
            --head "$BRANCH_NAME"
